### ISSUE TITLE
Apache please?

### ISSUE THREAD

**Issue by MartinMuzatko** [mybb/docker#4]
Is it possible to support an apache image? Is mybb apache compatible? this way, no nginx is needed.

**Comment by euantorano** [comment]
MyBB is completely compatible with Apache. Nginx is only used for this image as it is lighter weight (and faster in most cases) than Apache.

**Comment by kawaii** [comment]
It's also worth noting that this Docker image should be considered alpha/experimental software - and shouldn't be used in a production environment unless you're extremely experienced with both Docker and MyBB. I personally use this setup only for testing PRs and plugins since I find it easier than alternative methods of creating a MyBB development environment.

**Comment by MartinMuzatko** [comment]
With 50k+ Downloads, I am very certain that this is used in production and we use it in production too. It is the highest ranking image you can find on docker hub for mybb. I wasn't aware of any performance impact with apache vs fpm with nginx.

I wanted to use traefik to manage my reverse proxy, not nginx. But Traefik is not built to replace php/apache. It just routes containers to specific rules like host, pathprefix, etc.

I would be already happy with php executables built-in webserver (`php -S 0.0.0.0:80`)

I don't really grasp why FPM is a good fit for something that you want to access via a webserver anyway.
FPM provides no direct entry to the files via HTTP - right? 

Thank you for your advice and for sharing this docker image!

**Comment by euantorano** [comment]
I've just had a super brief look, and it looks like Apache can talk to PHP-FPM: https://www.interserver.net/tips/kb/apache-php-fpm-ubuntu-18-04/

I only use Nginx myself, so can't tell if these instructions are current or anything, and have no experience with Traefik.

**Comment by MartinMuzatko** [comment]
thank you, I will read through this. Thank you for the input
